[package]
name = "tokio_with_wasm"
version = "0.4.3"
edition = "2021"
license = "MIT"
description = "Mimicking tokio functionalies on web browsers"
repository = "https://github.com/cunarist/tokio-with-wasm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.68"
futures-channel = "0.3.30"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
web-sys = { version = "0.3.68", features = [
    'Worker',
    'WorkerOptions',
    'WorkerType',
    'DedicatedWorkerGlobalScope',
    'MessageEvent',
    'ErrorEvent',
    'Blob',
    "BlobPropertyBag",
    'Url',
] }
tokio = { version = "1", features = ["sync", "macros"] }
