[package]
name = "async_wasm_task"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "Manage the concurrency of async tasks in webassembly Rust"
repository = "https://github.com/cunarist/async-wasm-task"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.64"
futures-channel = "0.3.28"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.23", features = [
    'Worker',
    'DedicatedWorkerGlobalScope',
    'MessageEvent',
    'ErrorEvent',
    'Blob',
    "BlobPropertyBag",
    'Url',
] }
