[build]
# Tell Rust-analyzer to perform
# type checking and linting in webassembly mode.
# If you make any changes to this field,
# you might have to restart Rust-analyzer for the change to take effect.
target = "wasm32-unknown-unknown"
